image: docker:19.03.13

stages:
  - begin
  - maven deploy
  - docker deploy

cache:
  paths:
    - .m2/repository
  when: always

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  GIT_DEPTH: 1
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.13-dind

begin:
  stage: begin
  script:
    - echo 'hello'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual

maven-deploy-pom:
  stage: maven deploy
  image: maven:3.6.3-openjdk-17
  needs:
    - begin
  script:
    - 'cd platform-pom && mvn deploy -s ci_settings.xml && cd -'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

maven-deploy-client:
  stage: maven deploy
  image: maven:3.6.3-openjdk-17
  needs:
    - maven-deploy-pom
  script:
    - 'cd platform-client-spring-boot-starter && mvn deploy -s ci_settings.xml && cd -'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

docker-deploy-server:
  stage: docker deploy
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login $DOCKER_REGISTRY --username $DOCKER_REGISTRY_USER --password-stdin
    - cd platform-server
  script:
    - docker build -t TZQ/platform-server .
    - docker push TZQ/platform-server
  after_script:
    - cd -