image: maven:latest]

cache:
  paths:
    - .m2/repository/
    - target/

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GIT_DEPTH: 1

maven-deploy:
  image: maven:3.6.3-openjdk-17
  script:
    - 'cd platform-pom && mvn deploy -s ci_settings.xml && cd -'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
