stages:
  - deploy

cache:
  paths:
    - .m2/repository
  when: always

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  GIT_DEPTH: 1

maven-deploy:
  image: maven:3.6.3-openjdk-17
  stage: deploy
  script:
    - 'cd platform-pom && mvn -T 4 deploy -s ci_settings.xml && cd -'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual

sync-to-github:
  image: bitnami/git
  stage: deploy
  script:
    - git remote add origin https://${GITHUB_PAT}@github.com/${GITHUB_USERNAME}/${GITHUB_REPO}.git
    - git push -f
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH